langauge: java
install: skip
script:
  - mvn clean package assembly:single
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "target/SquadGoalsSMP-1.0-ALPHA.jar"
  skip_cleanup: true
branches:
  only:
    - master