name: SquadGoalsSMP
author: Block2Block
main: me.block2block.squadgoalssmp.Main
version: "1.0"
api-version: "1.14"
commands:
  balance:
    aliases: [bal,money,moneyz,howmuchdoihaveinthebank,howrichami,howpoorami,howbrokeami,hownotbrokeami,howmuchmoneydoihavetowaste]
    description: Check your balance.
    usage: /balance
  purge:
    description: Purge related commands! Server Admin Only.
    usage: Don't use it.
  pay:
    aliases: [charity,donate,giveoutmoneyz,idontwantthismoneyanymore,sharethewealth,ineedtohidethismoneyfromtheirs,ineedtohidethismoneyfromhmrc,takemyprecioushardearnedmoney,moneyodisapearo]
    description: Pay a user money.
    usage: /pay [user] [amount]
  updateecon:
    description: Updates Economy Values. Server Admin Only.
    usage: /updateecon
  team:
    aliases: [teams]
    description: Team related commands and subcommands.
    usage: /team [command arguments]
  trial:
    description: Trial related commands.
    usage: /trial [command arguments]
  whitelist:
    description: Whitelist players
    usage: /whitelist [command arguments]